// <auto-generated />
namespace ACME_REPOSITORY.MSSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class InitialUpload : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialUpload));
        
        string IMigrationMetadata.Id
        {
            get { return "201707141007284_InitialUpload"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
